#!/bin/zsh
if ! command -v conda &> /dev/null
then
    echo "conda is not installed. Please install Conda and rerun this script."
    exit 1
fi
if ! command -v git &> /dev/null
then
    echo "git could not be found, installing git..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install git
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo apt-get update
        sudo apt-get install git -y
    else
        echo "Unsupported OS. Please install git manually."
        exit 1
    fi
fi

git clone https://github.com/Xinglab/rmats-turbo.git
cd ./rmats-turbo
sed -n '/# >>> conda initialize >>>/,/# <<< conda initialize <<</p' ~/.zshrc > conda_init.sh
sed -i '/CONDA_ENV_PATH="\${SCRIPT_DIR}\/conda_envs\/rmats"/r conda_init.sh' ./build_rmats
./build_rmats --conda